# Create an EC2 key-pair
resource "aws_key_pair" "security_key" {
  key_name   = "todo-bastion-host-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvxd0CFLjK1R2LztDmuEB6YrRmvBWgkCNoYe1p7wQg+CxeLoIVbsxId94n570CLb2ZRywiRRslONuUakwCpj4RBa/Vf2jHDnRLgR0Bqeq23R342dJBYuhRNv5gXDcdifFDGtdPqReoRY5D+ZaG3XoFuuK5oQfgBnV3SnjXZYUDXXB9WELrdsTxRgL6/56Ql9jaPtwRXpV1SbJElev2Xs9XnPuSrRGv3AQxz+oMn2bH5nD1J1KCpYjc9OfIkxHB8zpehDZ5h/lHsiHSrDvG9qDInEhjoO6cQcReU3cKx8ecPJJELcfWXa7pqxFPEsCvi/zb+1ISInvTq8ZnbSoTi3b+NfXN5MccxaHdDvvS+A4Pzu4/akkhyH+lhb+m0YSq/Hp2qCUZeQuCE/xPo9rkFe+IZVsnhrnolo6k+jt8RgBRNH807nGWwhAa1DcNqOdnpO+J4geTPm+JzuITw+ttdiE5vHltmJpj80j4Khx696SE6e9thZcydpfNhyLBKo5LPVq+hHtEr6IYjeDIs2MbIC8kp2GCRmBDBaf/LoGm3UoOPUoYKytep2SXx9LNmPMBzYxjiHWwHrWlCbbEYLRwom9dMQyCOLoZavN2DvO8klCDJLGJKMEU2GxeYDP8ECCRRnrYjyfosLWqbbR3aSpuXeUJRa56UUGWLvYuVbpkjsCy5Q== deepak@PF1RN8ZY"
  }
#  IF YOU INTEND TO USE THIS CODE IN PRODUCTION, THEN YOU MUST GENERATE YOUR OWN KEY-PAIR USING THE SSH-KEYGEN COMMAND.
# REPLACE THE VALUE OF PUBLIC_KEY WITH YOUR OWN PUBLIC_KEY
# THE PRIVATE KEY-PAIR FILE MUST ALSO BE REPLACED AND TAKEN OUT OF SOURCE (VERSION) CONTROL.
